using System.Globalization;
using System.Text;
using ClaudeDashboard.App.Ui;
using ClaudeDashboard.Core;
using ClaudeDashboard.Tests.Fakes;

namespace ClaudeDashboard.Tests.Ui;

/// <summary>
/// The session title on the row (T1.24, issue #18; Design Document §9).
/// </summary>
/// <remarks>
/// <para>
/// View-model tests: the text, the tooltip and the accessible name, with no window. What the row
/// actually renders — and that it renders in both views — is asserted in <c>MainWindowTests</c>,
/// because only a realized template can show that.
/// </para>
/// <para>
/// <strong>The titles here are ugly on purpose.</strong> A title is arbitrary text written by
/// something outside this process — an operator with a keyboard, or a small model summarising
/// their first prompt — so the interesting cases are the emoji, the combining mark and the
/// newline, not "Director".
/// </para>
/// </remarks>
public sealed class SessionTitleRowTests
{
    /// <summary>A real title from this machine: 109 characters, and it starts like markup.</summary>
    /// <remarks>
    /// Kept verbatim from issue #18. It is the case that made truncation a guard rather than a
    /// nicety — untruncated it consumes the row — and it is also the case that would matter most
    /// if anything on this path ever interpreted the text instead of drawing it.
    /// </remarks>
    private const string CaveatTitle =
        "<local-command-caveat>Caveat: The messages below were generated by the user while running " +
        "local comm (Branch)";

    private static readonly DateTimeOffset At = FakeClock.DefaultStart;

    /// <summary>A session with no title renders exactly as it did before this feature.</summary>
    /// <remarks>
    /// Every property is asserted, not just the visible one. An empty prefix is what keeps the
    /// row free of a stray separator, and a null tooltip is what keeps an empty popup from
    /// opening on hover; either one wrong would be a visible defect on the majority of rows,
    /// since most sessions in the archive carry no title at all.
    /// </remarks>
    [Fact]
    public void A_session_with_no_title_renders_as_it_did_before()
    {
        var row = Row(title: null);

        Assert.False(row.HasTitle);
        Assert.Equal(string.Empty, row.TitleDisplay);
        Assert.Equal(string.Empty, row.TitlePrefix);
        Assert.Null(row.TitleTooltip);
        Assert.Equal(row.PromptSnippet, row.RowName);
    }

    /// <summary>The row reads <c>Director — run the tests</c>.</summary>
    [Fact]
    public void A_titled_row_puts_the_title_before_the_prompt()
    {
        var row = Row("Director", prompt: "run the tests");

        Assert.True(row.HasTitle);
        Assert.Equal("Director", row.TitleDisplay);
        Assert.Equal("Director — ", row.TitlePrefix);
        Assert.Equal("Director — run the tests", row.TitlePrefix + row.PromptSnippet);
    }

    /// <summary>
    /// <strong>The title costs the prompt nothing.</strong>
    /// </summary>
    /// <remarks>
    /// Issue #18 rules the title sits outside <see cref="SessionViewModel.SnippetLength"/>. The
    /// tempting implementation spends the title's characters out of the snippet's budget, which
    /// would silently shorten the context line on exactly the rows that have a name — and nothing
    /// would look broken, the prompt would just say a little less.
    /// </remarks>
    [Fact]
    public void The_prompt_keeps_its_whole_budget_when_a_title_is_present()
    {
        var prompt = new string('p', 400);

        var titled = Row("Director", prompt);
        var bare = Row(title: null, prompt);

        Assert.Equal(bare.PromptSnippet, titled.PromptSnippet);
        Assert.Equal(SessionViewModel.SnippetLength + 1, titled.PromptSnippet.Length);
    }

    /// <summary>Exactly at the budget: shown whole, and no tooltip.</summary>
    /// <remarks>
    /// A tooltip repeating text already on screen is noise, so the boundary is asserted from both
    /// sides — here and in the test below — rather than only where it truncates.
    /// </remarks>
    [Fact]
    public void A_title_of_exactly_forty_is_shown_whole_and_gets_no_tooltip()
    {
        var title = new string('a', SessionViewModel.TitleClusters);

        var row = Row(title);

        Assert.Equal(title, row.TitleDisplay);
        Assert.DoesNotContain("…", row.TitleDisplay, StringComparison.Ordinal);
        Assert.Null(row.TitleTooltip);
    }

    /// <summary>One character over truncates, and hovering shows the whole thing.</summary>
    [Fact]
    public void A_title_one_character_over_is_cut_and_gets_a_tooltip()
    {
        var title = new string('a', SessionViewModel.TitleClusters + 1);

        var row = Row(title);

        Assert.Equal(new string('a', SessionViewModel.TitleClusters) + "…", row.TitleDisplay);
        Assert.Equal(SessionViewModel.TitleClusters + 1, row.TitleDisplay.Length);
        Assert.Equal(title, row.TitleTooltip);
    }

    /// <summary>The long real title renders bounded, and unchanged as text.</summary>
    /// <remarks>
    /// Both halves matter. Bounded is the point of truncating; unchanged is the point of not
    /// interpreting — the title opens with something that looks like a tag, and the row prints it
    /// as the characters it is.
    /// </remarks>
    [Fact]
    public void The_caveat_title_renders_bounded_and_unchanged()
    {
        var row = Row(CaveatTitle);

        Assert.Equal("<local-command-caveat>Caveat: The messag…", row.TitleDisplay);
        Assert.Equal(SessionViewModel.TitleClusters + 1, row.TitleDisplay.Length);
        Assert.Equal(CaveatTitle, row.TitleTooltip);
    }

    /// <summary>
    /// <strong>The cut never splits a grapheme cluster.</strong>
    /// </summary>
    /// <remarks>
    /// <para>
    /// Each of these puts a multi-character cluster across the boundary. Cutting by UTF-16 code
    /// unit — which is what the prompt snippet still does — leaves a lone surrogate for three of
    /// them: measured on .NET 10, the result does not round-trip through UTF-8 and draws as the
    /// replacement glyph. The fourth loses its accent and stays legible, which is the quieter
    /// version of the same defect.
    /// </para>
    /// <para>
    /// The assertion is that the whole cluster survives, so a cut that produced a lone surrogate
    /// would fail on the value rather than on some proxy for it.
    /// </para>
    /// </remarks>
    [Theory]
    [InlineData("\U0001F44D", "thumbs up")]
    [InlineData("\U0001F468\u200D\U0001F469\u200D\U0001F467", "family, joined by ZWJ")]
    [InlineData("\U0001F1EC\U0001F1E7", "a flag, two regional indicators")]
    [InlineData("e\u0301", "e with a combining acute")]
    public void A_cluster_straddling_the_cut_survives_whole(string cluster, string description)
    {
        var title = new string('a', SessionViewModel.TitleClusters - 1) + cluster + " and more";

        var shown = Row(title).TitleDisplay;

        Assert.True(
            shown.EndsWith(cluster + "…", StringComparison.Ordinal),
            $"The {description} did not survive the cut whole.");

        // And the result is a well-formed string. A lone surrogate does not round-trip through
        // UTF-8, which is the objective form of "draws as a replacement glyph".
        Assert.Equal(shown, Encoding.UTF8.GetString(Encoding.UTF8.GetBytes(shown)));
    }

    /// <summary>
    /// <strong>Forty clusters is not a bound on length, so a second bound does the work.</strong>
    /// </summary>
    /// <remarks>
    /// Measured: forty clusters of a letter plus two hundred combining marks each is 8,040
    /// characters and passes a forty-cluster cut untouched. Without the character ceiling the row
    /// would be handed the whole of it to lay out. The ceiling cuts on a cluster boundary too, so
    /// the second bound cannot reintroduce the split glyph the first one avoids.
    /// </remarks>
    [Fact]
    public void A_title_of_forty_enormous_clusters_is_still_bounded()
    {
        var title = string.Concat(
            Enumerable.Repeat("a" + new string('\u0301', 200), SessionViewModel.TitleClusters));

        var row = Row(title);

        Assert.True(
            row.TitleDisplay.Length <= SessionViewModel.TitleCharacterCeiling + 1,
            $"The row was handed {row.TitleDisplay.Length} characters to lay out.");

        Assert.True(row.TitleDisplay.EndsWith('…'));
        Assert.Equal(title, row.TitleTooltip);
    }

    /// <summary>
    /// <strong>A title with line breaks becomes one line.</strong>
    /// </summary>
    /// <remarks>
    /// A <c>TextBlock</c> breaks on a newline whatever the wrapping mode, so a two-line title
    /// doubles the row's height however few characters it holds — a bound that counting clusters
    /// does not cover. Tabs and other control characters go the same way, and runs collapse to one
    /// space so the result reads as a line rather than as a paragraph with the breaks removed.
    /// </remarks>
    [Theory]
    [InlineData("one\ntwo", "one two")]
    [InlineData("one\r\ntwo", "one two")]
    [InlineData("one\ttwo", "one two")]
    [InlineData("one\u2028two", "one two")]
    [InlineData("  padded  ", "padded")]
    [InlineData("many   spaces", "many spaces")]
    public void A_title_is_folded_to_a_single_line(string title, string expected)
    {
        Assert.Equal(expected, Row(title).TitleDisplay);
    }

    /// <summary>Folding keeps the zero-width joiner, because it holds a cluster together.</summary>
    /// <remarks>
    /// The joiner is in the Format category, which sits next to Control in any list of "characters
    /// that are not letters". Stripping the two together would shatter exactly the graphemes the
    /// cluster cut exists to keep whole — a fix for one hazard quietly undoing the other.
    /// </remarks>
    [Fact]
    public void Folding_keeps_the_joiner_that_holds_an_emoji_together()
    {
        const string Family = "\U0001F468\u200D\U0001F469\u200D\U0001F467";

        Assert.Equal(Family, Row(Family).TitleDisplay);
    }

    /// <summary>A title that is nothing but whitespace is no title at all.</summary>
    /// <remarks>
    /// The Registry already refuses to latch one, so this is the second line of defence: a value
    /// reaching the row from a replayed session or a future latch rule must not produce a bare
    /// separator sitting in front of the prompt.
    /// </remarks>
    [Theory]
    [InlineData(" ")]
    [InlineData("\n\n")]
    [InlineData("\t")]
    public void A_whitespace_title_shows_nothing(string title)
    {
        var row = Row(title);

        Assert.False(row.HasTitle);
        Assert.Equal(string.Empty, row.TitlePrefix);
    }

    /// <summary>
    /// <strong>A screen reader hears the title as well as the prompt.</strong>
    /// </summary>
    /// <remarks>
    /// The row's <c>AutomationProperties.Name</c> used to bind the prompt alone, so the name was
    /// simply absent from the accessible tree. Asserting equality with what the row draws — rather
    /// than "the name contains the title" — is what stops the two drifting apart later.
    /// </remarks>
    [Fact]
    public void The_accessible_name_is_exactly_what_the_row_draws()
    {
        var row = Row("Director", prompt: "run the tests");

        Assert.Equal("Director — run the tests", row.RowName);
        Assert.Equal(row.TitlePrefix + row.PromptSnippet, row.RowName);
    }

    /// <summary>A truncated title is truncated in the accessible name too, not expanded there.</summary>
    /// <remarks>
    /// The accessible name describes the row as rendered; the whole title stays reachable through
    /// the tooltip. A name carrying the untruncated value would make the two disagree, and the
    /// pathological title of the ceiling test would be read out in full.
    /// </remarks>
    [Fact]
    public void The_accessible_name_carries_the_shown_title_rather_than_the_whole_one()
    {
        var row = Row(CaveatTitle, prompt: "run the tests");

        Assert.StartsWith("<local-command-caveat>Caveat: The messag… — ", row.RowName, StringComparison.Ordinal);
        Assert.DoesNotContain("(Branch)", row.RowName, StringComparison.Ordinal);
    }

    private static SessionViewModel Row(string? title, string prompt = "run the tests") =>
        new(
            new Session
            {
                Id = new SessionId("88a85f67-4c21-4f0e-9d3b-a1b2c3d4e5f6"),
                State = SessionState.Working,
                Latest = new Exchange { Prompt = prompt, StartedAt = At },
                Cwd = @"C:\w",
                WorkspaceGroup = GroupKeys.ForWorkspace(@"C:\w"),
                EnteredAt = At,
                LastActivity = At,
                LastHeardAt = At,
                Title = title,
            },
            new MotionPolicy(() => false, observeChanges: false));
}
